[package]
name = "invariant-protocol"
version = "0.1.0"
authors = ["Invariant Labs"]
edition = "2021"

[dependencies]
# local
decimal = { path = "src/decimal" }
# math = { path = "src/math", default-features = false, features = [
#   "ink-as-dependency",
# ]}
math = { path = "src/math", default-features = false}
tracable_result = { path = "src/tracable_result" }

# ink
ink = { version = "4.3.0", default-features = false}
ink_env = { version = "4.3.0", default-features = false }
scale = { package = "parity-scale-codec", version = "3.6.5", default-features = false, features = [
  "derive",
] }
scale-info = { version = "2.9.0", default-features = false, features = [
  "derive",
], optional = true }
openbrush = { git = "https://github.com/Brushfam/openbrush-contracts", branch = "develop", default-features = false, features = [
  "psp22",
  "ownable",
] }

[dev-dependencies]
ink_e2e = "4.2.0"

[lib]
name = "flipper"
path = "src/lib.rs"

[features]
default = ["std"]
std = ["ink/std", "ink_env/std", "scale/std", "scale-info/std",
# Brush dependency
"openbrush/std",]
ink-as-dependency = []
e2e-tests = []