[package]
name = "math"
version = "0.1.0"
edition = "2021"

[dependencies]
decimal = { path = "../decimal" }
tracable_result = { path = "../tracable_result" }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = [
  "derive",
] }
scale-info = { version = "2.6", default-features = false, features = [
  "derive",
], optional = true }
