[package]
name = "math"
version = "0.1.0"
edition = "2021"

[dependencies]
decimal = { path = "../decimal" }
traceable_result = { path = "../traceable_result" }

# ink
ink = { version = "4.3.0", default-features = false }
scale = { package = "parity-scale-codec", version = "3.6.5", default-features = false, features = [
  "derive",
] }
scale-info = { version = "2.9.0", default-features = false, features = [
  "derive",
], optional = true }

[lib]
name = "math"
path = "./src/lib.rs"

[features]
default = ["std"]
std = ["ink/std", "scale/std", "scale-info/std"]
ink-as-dependency = []
e2e-tests = []
