[package]
name = "math"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]
edition = "2018"
rust-version = "1.57"

[lib]
path = "lib.rs"
# crate-type = ["cdylib", "rlib"]

[dependencies]
# wasm-bindgen = {version = "0.2.89", default-features = false}
# serde = { version = "1.0", features = ["derive"], default-features = false}
# serde-wasm-bindgen = {version = "0.6.3", default-features = false}
# tsify = {version = "0.4.5", default-features = false}

decimal = { path= "../decimal" }
traceable_result = { path = "../traceable_result" }

# ink
ink = { version = "4.2.0", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = [
  "derive",
] }
scale-info = { version = "2.6", default-features = false, features = [
  "derive",
] }


[features]
default = ["std"]
std = ["ink/std", "scale/std", "scale-info/std", ] #"serde/std","wasm-bindgen/std"
ink-as-dependency = []