name: Unit and e2e tests

on:
  pull_request:
    branches:
      - master

jobs:
  checks:
    name: Uint and e2e tests + linit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Cache Crates
        uses: actions/cache@v3
        with:
          path: ~/.cargo 
          key: ${{ runner.os }}-rust-${{ hashFiles('rust-toolchain.toml') }}
          restore-keys: |
            ${{ runner.os }}-rust

      # - name: Install Rust toolchain
      #   uses: Cardinal-Cryptography/github-actions/install-rust-toolchain@v1

      - name: Install Rust toolchain
        run: |
          rustup show
          rustup component add rust-src

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          # args: --all-targets -- --no-deps -D warnings (TODO: fix clippy warnings first)



      - name: Check if cargo-contract exists
        id: check-cargo-contract
        continue-on-error: true
        run: cargo contract --version

      - name: Install Protobuf
        if: ${{ steps.check-cargo-contract.outcome == 'failure' }}
        run: |
          sudo apt-get install -y protobuf-compiler libprotobuf-dev
      
        
      - name: Install substrate-contracts-node
        if: ${{ steps.check-cargo-contract.outcome == 'failure' }}
        run: |
          cargo install cargo-dylint dylint-link
          cargo install --force --locked cargo-contract

      # TODO: try downlaod binary from github release
      # - name: Install substrate-contracts-node
      #   if: ${{ steps.check-cargo-contract.outcome == 'failure' }}
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: install
      #     args: --force --locked contracts-node

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features e2e-tests

  build:
    name: Build the contract
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Cache Crates
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-contract-build-env-${{ hashFiles('rust-toolchain.toml') }}

      - name: Install Rust toolchain
        uses: Cardinal-Cryptography/github-actions/install-rust-toolchain@v1

      - name: Install cargo contract
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --locked cargo-contract

      - name: Build contract
        uses: actions-rs/cargo@v1
        with:
          command: contract
          args: build --release

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features e2e-tests